### ISSUE TITLE
[Fix] Fix funky bivariate animations 

### ISSUE THREAD

**Issue by qpmnguyen** [qpmnguyen/DIFUSE_2020_EddyCovariance#2]
**Issue description**: Some funky stuff with the bivariate animations  
**Tasks to do**:  
- [x] Re-scale at each time step (At each time step the variables contract and expand and not properly scaled. At every time step the graph should be rescaled such that the points are adequately spread out) 
- [x] Display the covariance calculation at each time point  
- [x] Add an option to see all points overall (instead of only points at each time step -- two buttons maybe?) 
- [x] Fix overall plot where the trendline was behind the point cloud  
- [x] Remove 20 minute option
